package Interface;

import org.openqa.selenium.By;

public class I_TemplatePage {

	public static By txt_Search = By.xpath("//div[@class='styles__leftPanel___2uXx1  styles__column___3WfRo']//input");
	public static By btn_Search = By.xpath("//div[@class='styles__leftPanel___2uXx1  styles__column___3WfRo']//div[@class='styles__searchSVG___26P3w']");
	public static By lbl_CategoryTitle = By.id("templatesH1");
	public static By lbl_TemplateTourGuide = By.xpath("//div[@class='styles__root___i5NK6']");

	// categories
	public static By lnk_CatRecommended = By.id("cat-recommended");
	public static By lnk_CatFeatured = By.id("cat-featured");
	public static By lnk_CatLayouts = By.id("cat-layouts");
	public static By lnk_CatSeeAll = By.id("cat-see-all-templates");
	public static By lnk_CatInfographics = By.id("cat-infographics");
	public static By lnk_CatPresentations = By.id("cat-presentations");
	public static By lnk_CatReports = By.id("cat-reports");
	public static By lnk_CatCharts = By.id("cat-charts");
	public static By lnk_CatMindMaps = By.id("cat-mind-maps");
	public static By lnk_CatRoadMaps = By.id("cat-roadmaps");
	public static By lnk_CatBrochures = By.id("cat-brochures");
	public static By lnk_CatResumes = By.id("cat-resumes");
	public static By lnk_CatEducation = By.id("cat-education");
	public static By lnk_CatCertificates = By.id("cat-certificates");
	public static By lnk_CatLetterHeads = By.id("cat-letterheads");
	public static By lnk_CatWhitePapers = By.id("cat-white-papers");
	public static By lnk_Catproposals = By.id("cat-proposals");
	public static By lnk_CatPosters = By.id("cat-posters");
	public static By lnk_CatFlyers = By.id("cat-flyers");
	public static By lnk_CatNewLetters = By.id("cat-newsletters");
	public static By lnk_CatInvitations = By.id("cat-invitations");
	public static By lnk_CatCards = By.id("cat-cards");
	public static By lnk_CatCoupons = By.id("cat-coupons");
	public static By lnk_CatSocialMedia = By.id("cat-social-media");
	public static By lnk_CatLogos = By.id("cat-logos");
	public static By lnk_CatEbooks = By.id("cat-ebooks");
	public static By lnk_CatBanners = By.id("cat-banners");
	public static By lnk_CatMenus = By.id("cat-menus");

	// subcategories
	public static By lnk_SubcatInformational = By.id("infographics-informational");
	public static By lnk_SubcatStatistical = By.id("infographics-statistical");
	public static By lnk_SubcatProcess = By.id("infographics-process");
	public static By lnk_SubcatGeographic = By.id("infographics-geographic");
	public static By lnk_SubcatTimeline = By.id("infographics-timeline");
	public static By lnk_SubcatComparison = By.id("infographics-comparison");
	public static By lnk_SubcatList = By.id("infographics-list");
	public static By lnk_SubcatFunData = By.id("infographics-fun-data");
	public static By lnk_SubcatTutorial = By.id("infographics-tutorials");
	public static By lnk_SubcatNonprofit = By.id("infographics-nonprofit");
	public static By lnk_SubcatHumanResources = By.id("infographics-human-resources");
	public static By lnk_SubcatRealEstate = By.id("infographics-real-estate");
	public static By lnk_SubcatPitchDecks = By.id("presentations-pitch-decks");
	public static By lnk_SubcatPreBusiness = By.id("presentations-business");
	public static By lnk_SubcatCreative = By.id("presentations-creative");
	public static By lnk_SubcatEngaging = By.id("presentations-engaging");
	public static By lnk_SubcatAnnual = By.id("reports-annual");
	public static By lnk_SubcatMonthly = By.id("reports-monthly");
	public static By lnk_SubcatSurveyResults = By.id("reports-survey-results");
	public static By lnk_SubcatReportNonprofit = By.id("reports-nonprofit");
	public static By lnk_SubcatReportMarketing = By.id("reports-marketing");
	public static By lnk_SubcatPie = By.id("charts-pie");
	public static By lnk_SubcatBar = By.id("charts-bar");
	public static By lnk_SubcatLine = By.id("charts-line");
	public static By lnk_SubcatDiagram = By.id("charts-venn-diagram");
	public static By lnk_SubcatBubble = By.id("charts-bubble");
	public static By lnk_SubcatArea = By.id("charts-area");
	public static By lnk_SubcatFlow = By.id("charts-flow");
	public static By lnk_SubcatMap = By.id("charts-map");
	public static By lnk_SubcatScatterplot = By.id("charts-scatterplot");
	public static By lnk_SubcatStacked = By.id("charts-stacked");
	public static By lnk_SubcatWordCloud = By.id("charts-word-cloud");
	public static By lnk_SubcatSingle = By.id("charts-single");
	public static By lnk_SubcatMixed = By.id("charts-mixed");
	public static By lnk_SubcatEditorial = By.id("charts-editorial");
	public static By lnk_SubcatMindMapBusiness = By.id("mind-maps-business");
	public static By lnk_SubcatMindMapSimple = By.id("mind-maps-simple");
	public static By lnk_SubcatRoadMapProduct = By.id("roadmaps-product");
	public static By lnk_SubcatMarketing = By.id("roadmaps-marketing");
	public static By lnk_SubcatTriFold = By.id("brochures-tri-fold");
	public static By lnk_SubcatTravel = By.id("brochures-travel");
	public static By lnk_SubcatProcessional = By.id("resumes-professional");
	public static By lnk_SubcatCoverLetter = By.id("resumes-cover-letters");
	public static By lnk_SubcatTeachingAids = By.id("education-teaching-aids");
	public static By lnk_SubcatLessonPlans = By.id("education-lesson-plans");
	public static By lnk_SubcatRecognition = By.id("certificates-recognition");
	public static By lnk_SubcatComletion = By.id("certificates-completion");
	public static By lnk_SubcatLetterHeadBusiness = By.id("letterheads-business");
	public static By lnk_SubcatSimple = By.id("white-papers-simple");
	public static By lnk_SubcatProposalBusiness = By.id("proposals-business");
	public static By lnk_SubcatPosterEvent = By.id("posters-event");
	public static By lnk_SubcatPosterHoliday = By.id("posters-holiday");
	public static By lnk_SubcatFlyerBusiness = By.id("flyers-business");
	public static By lnk_SubcatFlyerProduct = By.id("flyers-product");
	public static By lnk_SubcatFlyerEvent = By.id("flyers-event");
	public static By lnk_SubcatNewLetterEvent = By.id("newsletters-event");
	public static By lnk_SubcatNewLetterHoliday = By.id("newsletters-holiday");
	public static By lnk_SubcatSchool = By.id("newsletters-school");
	public static By lnk_SubcatInviHoliday = By.id("invitations-holiday");
	public static By lnk_SubcatWedding = By.id("invitations-wedding");
	public static By lnk_SubcatInviBirthday = By.id("invitations-birthday");
	public static By lnk_SubcatBabyShower = By.id("invitations-baby-shower");
	public static By lnk_SubcatBridalShower = By.id("invitations-bridal-shower");
	public static By lnk_SubcatSaveTheDate = By.id("invitations-save-the-date");
	public static By lnk_SubcatParty = By.id("invitations-party");
	public static By lnk_SubcatCardBirthday = By.id("cards-birthday");
	public static By lnk_SubcatCongratulation = By.id("cards-congratulations");
	public static By lnk_SubcatGreeting = By.id("cards-greeting");
	public static By lnk_SubcatThankYou = By.id("cards-thank-you");
	public static By lnk_SubcatHoliday = By.id("cards-holiday");
	public static By lnk_SubcatThanksGiving = By.id("cards-thanksgiving");
	public static By lnk_SubcatChristmas = By.id("cards-christmas");
	public static By lnk_SubcatHannukah = By.id("cards-hannukah");
	public static By lnk_SubcatMothersDay = By.id("cards-mothers-day");
	public static By lnk_SubcatFathersDay = By.id("cards-fathers-day");
	public static By lnk_SubcatGetWell = By.id("cards-get-well");
	public static By lnk_SubcatGiftCertificates = By.id("coupons-gift-certificates");
	public static By lnk_SubcatVouchers = By.id("coupons-vouchers");
	public static By lnk_SubcatInstagram = By.id("social-media-instagram");
	public static By lnk_SubcatFacebook = By.id("social-media-facebook");
	public static By lnk_SubcatPinterest = By.id("social-media-pinterest");
	public static By lnk_SubcatTwiter = By.id("social-media-twitter");
	public static By lnk_SubcatLinkedIn = By.id("social-media-linkedin");
	public static By lnk_SubcatLogoBusiness = By.id("logos-business");
	public static By lnk_SubcatLogoCreative = By.id("logos-creative");
	public static By lnk_SubcatEbookSimple = By.id("ebooks-simple");
	public static By lnk_SubcatBlog = By.id("banners-blog");
	public static By lnk_SubcatEmail = By.id("banners-email");
	public static By lnk_SubcatBannerFacebook = By.id("banners-facebook");
	public static By lnk_SubcatBannerInstagram = By.id("banners-instagram");
	public static By lnk_SubcatBannerTwitter = By.id("banners-twitter");
	public static By lnk_SubcatBannerLinkedIn = By.id("banners-linkedin");
	public static By lnk_SubcatBannerYoutube = By.id("banners-youtube");
	public static By lnk_SubcatRestaurant = By.id("menus-restaurant");
	
	public static By btn_CreateFromPreview = By.id("preview-create-btn");
	public static By btn_UpgradeFromPreview = By.id("preview-upgrade-btn");
}
